# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.4
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_wazlibs', [dirname(__file__)])
        except ImportError:
            import _wazlibs
            return _wazlibs
        if fp is not None:
            try:
                _mod = imp.load_module('_wazlibs', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _wazlibs = swig_import_helper()
    del swig_import_helper
else:
    import _wazlibs
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class WAProviderPluginProcess(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, WAProviderPluginProcess, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, WAProviderPluginProcess, name)
    __repr__ = _swig_repr
    def __init__(self): 
        this = _wazlibs.new_WAProviderPluginProcess()
        try: self.this.append(this)
        except: self.this = this
    __swig_setmethods__["isUniqueInstance"] = _wazlibs.WAProviderPluginProcess_isUniqueInstance_set
    __swig_getmethods__["isUniqueInstance"] = _wazlibs.WAProviderPluginProcess_isUniqueInstance_get
    if _newclass:isUniqueInstance = _swig_property(_wazlibs.WAProviderPluginProcess_isUniqueInstance_get, _wazlibs.WAProviderPluginProcess_isUniqueInstance_set)
    __swig_setmethods__["initType"] = _wazlibs.WAProviderPluginProcess_initType_set
    __swig_getmethods__["initType"] = _wazlibs.WAProviderPluginProcess_initType_get
    if _newclass:initType = _swig_property(_wazlibs.WAProviderPluginProcess_initType_get, _wazlibs.WAProviderPluginProcess_initType_set)
    __swig_setmethods__["account"] = _wazlibs.WAProviderPluginProcess_account_set
    __swig_getmethods__["account"] = _wazlibs.WAProviderPluginProcess_account_get
    if _newclass:account = _swig_property(_wazlibs.WAProviderPluginProcess_account_get, _wazlibs.WAProviderPluginProcess_account_set)
    def accountValueAsString(self, *args): return _wazlibs.WAProviderPluginProcess_accountValueAsString(self, *args)
    __swig_setmethods__["accountId"] = _wazlibs.WAProviderPluginProcess_accountId_set
    __swig_getmethods__["accountId"] = _wazlibs.WAProviderPluginProcess_accountId_get
    if _newclass:accountId = _swig_property(_wazlibs.WAProviderPluginProcess_accountId_get, _wazlibs.WAProviderPluginProcess_accountId_set)
    __swig_destroy__ = _wazlibs.delete_WAProviderPluginProcess
    __del__ = lambda self : None;
WAProviderPluginProcess_swigregister = _wazlibs.WAProviderPluginProcess_swigregister
WAProviderPluginProcess_swigregister(WAProviderPluginProcess)

# This file is compatible with both classic and new-style classes.


