#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Copyright (c) 2012, Tarek Galal <tarek@wazapp.im>

This file is part of Wazapp, an IM application for Meego Harmattan platform that
allows communication with Whatsapp users

Wazapp is free software: you can redistribute it and/or modify it under the 
terms of the GNU General Public License as published by the Free Software 
Foundation, either version 2 of the License, or (at your option) any later 
version.

Wazapp is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
Wazapp. If not, see http://www.gnu.org/licenses/.
'''
from Libs.wazlibs import WAProviderPluginProcess
from PySide.QtGui import QApplication
import sys
from Registration.registrationhandler import RegistrationUI

if __name__ == "__main__":
    
    app = QApplication(sys.argv)

    pp = WAProviderPluginProcess();
    
    ui = RegistrationUI(pp.accountId)
    ui.engine().quit.connect(app.quit)

    ui.showFullScreen();
    
    sys.exit(app.exec_())
    