#!/usr/bin/python
# -*- coding: utf-8 -*-
'''
Copyright (c) 2012, Tarek Galal <tarek@wazapp.im>

This file is part of Wazapp, an IM application for Meego Harmattan platform that
allows communication with Whatsapp users

Wazapp is free software: you can redistribute it and/or modify it under the 
terms of the GNU General Public License as published by the Free Software 
Foundation, either version 2 of the License, or (at your option) any later 
version.

Wazapp is distributed in the hope that it will be useful, but WITHOUT ANY 
WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. See the GNU General Public License for more details.

You should have received a copy of the GNU General Public License along with 
Wazapp. If not, see http://www.gnu.org/licenses/.
'''
import os
import sys
from PySide.QtGui import QApplication
import PySide
from wamanager import WAManager
from PySide import QtCore

#from waxmpp import WAXMPP
#from utilities import Utilities


	
if __name__ == "__main__":

	if os.path.isfile("/home/user/.wazapp/log.txt"):
		os.rename("/home/user/.wazapp/log.txt","/home/user/.wazapp/previows-log.txt")
	if not os.path.exists("/home/user/MyDocs/Wazapp/media/contacts"):
		os.makedirs("/home/user/MyDocs/Wazapp/media/contacts")

	linuxCodec = QtCore.QTextCodec.codecForName("UTF-8")
	QtCore.QTextCodec.setCodecForTr(linuxCodec)
	QtCore.QTextCodec.setCodecForCStrings(linuxCodec)
	QtCore.QTextCodec.setCodecForLocale(linuxCodec)
	
	lang_name = unicode(QtCore.QLocale.system().name())
	translator = QtCore.QTranslator()
	translator.load("/opt/waxmppplugin/bin/wazapp/i18n/tr_" + lang_name[:2] + ".qm")
	app = QApplication(sys.argv)
	app.installTranslator(translator)
	#PySide.QtGui.QErrorMessage.qtHandler().show()
	wam = WAManager(app)

	
	sys.exit(app.exec_())
