#!/usr/bin/python
# -*- coding: utf-8 -*-
import sys
from PySide.QtGui import QApplication
import PySide
from wamanager import WAManager


#from waxmpp import WAXMPP
#from utilities import Utilities


	
if __name__ == "__main__":

	
	app = QApplication(sys.argv)
	#PySide.QtGui.QErrorMessage.qtHandler().show()
	wam = WAManager(app)
	
	sys.exit(app.exec_())
